### PR TITLE
Bubble sort

### PR DESCRIPTION
**Pull request by Ispirett**
Thanks for you time

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, good job on your first ruby project. Although one function is missing which is `bubble_sort_by` that will get block as well.
Once added, kindly resubmit for review.

**Comment by Ispirett** [comment]
Ok sorry I did not notice that.

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, kindly look into the project description. Here is the `bubble_sort_by` which you need to try instead of updating bubble_sort. Both functions are different, one accepts array while other accept block as well.


> Now create a similar method called #bubble_sort_by which sorts an array by accepting a block. Remember to use yield inside your method definition to accomplish this. The block will have two arguments that represent the two elements of the array that are currently being compared. The block’s return will be similar to the spaceship operator you learned about before: If the result of the block execution is negative, the element on the left is “smaller” than the element on the right. 0 means both elements are equal. A positive result means the left element is greater. Use the block’s return value to sort your array.

**Review by inhaq — CHANGES_REQUESTED** [review]
Good job. Kindly remove comments and `puts` from the code. Also, improve `bubble_sort_by` which should work in both ways, with and without block.

**Review by inhaq — APPROVED** [review]
It's 👍🏻go ahead and submit the project completion form.

**Comment by Ispirett** [comment]
Thank you have a great day.

**Pull request merged**
